/*
 * marketingHome.java
 *
 * Created on 28 November, 2009, 1:31 AM
 */


package marketing;
import java.awt.Dimension;
import javax.swing.table.AbstractTableModel;
import stock.Product;
import stock.ProductFew;
import stock.Raw;
import javax.swing.*;
import stock.RawFew;
/**
 *
 * @author  rishabh
 */
public class marketingHome extends javax.swing.JFrame {
    //setPrefardSize(new Dimention(100,100));
   viewCustomers viewcustomer;
   Product product_view;
   ProductFew productfew;
    Raw raw;
    RawFew rawfew;
    viewPayment payment_view; 
    viewAllOrders view_all_orders;
    viewFewOrders view_few_orders;
     viewOrderDetail view_full_order_detail;
    IDOrderDetail idorder;
    addCustomer add_cust;
    updateCustomers updatecust;
    addPayment addpayment;
     addOrder addorder;
    updatePayment updatepayment;
  updateOrder updateorder;
deleteOrder deleteorder;
deleteCustomer deletecustomer;
deletePayment deletepayment;
//JButton jb=new JButton("click here");
    /**
     * Creates new form marketingHome
     */
    public marketingHome() {
        //setSize(500,500);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);

 setPreferredSize(new Dimension(500,500));
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        orders = new javax.swing.JMenu();
        view_order = new javax.swing.JMenu();
        view_orders = new javax.swing.JMenu();
        last_ten_orders = new javax.swing.JMenuItem();
        full_table_order = new javax.swing.JMenuItem();
        view_order_detail = new javax.swing.JMenu();
        order_detail_by_id = new javax.swing.JMenuItem();
        full_order_detail = new javax.swing.JMenuItem();
        add_order = new javax.swing.JMenuItem();
        delete_order = new javax.swing.JMenuItem();
        update_order = new javax.swing.JMenuItem();
        payment = new javax.swing.JMenu();
        add_payment = new javax.swing.JMenuItem();
        update_payment = new javax.swing.JMenuItem();
delete_payment = new javax.swing.JMenuItem();
        view_payment = new javax.swing.JMenuItem();
        customers = new javax.swing.JMenu();
        view_customers = new javax.swing.JMenuItem();
        add_customer = new javax.swing.JMenuItem();
        delete_customer = new javax.swing.JMenuItem();
        update_customer = new javax.swing.JMenuItem();
        stock = new javax.swing.JMenu();
        view_raw_stack = new javax.swing.JMenu();
        last_ten_raw = new javax.swing.JMenuItem();
        full_table_raw = new javax.swing.JMenuItem();
        view_product_stock = new javax.swing.JMenu();
        last_ten_product = new javax.swing.JMenuItem();
        full_table_product = new javax.swing.JMenuItem();
        product = new javax.swing.JMenu();
        view_product = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        orders.setText("orders");
        view_order.setText("view");
        view_orders.setText("view orders");
        view_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ordersActionPerformed(evt);
            }
        });

        last_ten_orders.setText("show last ten orders");
        last_ten_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_ten_ordersActionPerformed(evt);
            }
        });

        view_orders.add(last_ten_orders);

        full_table_order.setText("show all orders");
        full_table_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_table_orderActionPerformed(evt);
            }
        });

        view_orders.add(full_table_order);

        view_order.add(view_orders);

        view_order_detail.setText("view order details");
        order_detail_by_id.setText("view order detail by ID");
        order_detail_by_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_detail_by_idActionPerformed(evt);
            }
        });

        view_order_detail.add(order_detail_by_id);

        full_order_detail.setText("show detail of all orders");
        full_order_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_order_detailActionPerformed(evt);
            }
        });

        view_order_detail.add(full_order_detail);

        view_order.add(view_order_detail);

        orders.add(view_order);

        add_order.setText("add new order");
        add_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_orderActionPerformed(evt);
            }
        });

        orders.add(add_order);

        delete_order.setText("delete existing order");
 
delete_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_orderActionPerformed(evt);
            }        }); 
        orders.add(delete_order);

        update_order.setText("update a order");
update_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_orderActionPerformed(evt);
            }        }); 
orders.add(update_order);

        jMenuBar1.add(orders);

        payment.setText("payment");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        add_payment.setText("add payment detail");
        add_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_paymentActionPerformed(evt);
            }
        });

        payment.add(add_payment);

        update_payment.setText("update payment detail");
        update_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_paymentActionPerformed(evt);
            }
        });

        payment.add(update_payment);

        view_payment.setText("view payment detail");
        view_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_paymentActionPerformed(evt);
            }
        });
 payment.add(view_payment);
        payment.add(delete_payment);
delete_payment.setText("delete payment detail");
        delete_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_paymentActionPerformed(evt);
            }
        });

        payment.add(delete_payment);

        jMenuBar1.add(payment);

        customers.setText("customers");
        customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersActionPerformed(evt);
            }
        });

        view_customers.setText("view customers");
        view_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_customersActionPerformed(evt);
            }
        });

        customers.add(view_customers);

        add_customer.setText("Add Customer");
        add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_customerActionPerformed(evt);
            }
        });

        customers.add(add_customer);

        delete_customer.setText("Delete Customer");

        delete_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_customerActionPerformed(evt);
            }
        });
        customers.add(delete_customer);

        update_customer.setText("Update Customer");
        update_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_customerActionPerformed(evt);
            }
        });

        customers.add(update_customer);

        jMenuBar1.add(customers);

        stock.setText("stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        view_raw_stack.setText("view raw stack");
        last_ten_raw.setText("show last 10 entries");
        last_ten_raw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_ten_rawActionPerformed(evt);
            }
        });

        view_raw_stack.add(last_ten_raw);

        full_table_raw.setText("show all table entries");
        full_table_raw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_table_rawActionPerformed(evt);
            }
        });

        view_raw_stack.add(full_table_raw);

        stock.add(view_raw_stack);

        view_product_stock.setText("view product stock");
        view_product_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_product_stockActionPerformed(evt);
            }
        });

        last_ten_product.setText("show last 10 entries");
        last_ten_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_ten_productActionPerformed(evt);
            }
        });

        view_product_stock.add(last_ten_product);

        full_table_product.setText("show all table entries");
        full_table_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_table_productActionPerformed(evt);
            }
        });

        view_product_stock.add(full_table_product);

        stock.add(view_product_stock);

        jMenuBar1.add(stock);

        product.setText("prodcut");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        view_product.setText("view all products");
        view_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_productActionPerformed(evt);
            }
        });

        product.add(view_product);

        jMenuBar1.add(product);

        setJMenuBar(jMenuBar1);

       
        pack();
    }// </editor-fold>//GEN-END:initComponents

 private void add_orderActionPerformed(java.awt.event.ActionEvent evt) {                                              
// TODO add your handling code here:                                          
        addorder=new addOrder();
        getContentPane().removeAll();
        add(addorder);
        addorder.setVisible(false);
        addorder.setVisible(true);
    }  
           
    private void add_paymentActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
        addpayment=new addPayment();
        getContentPane().removeAll();
        add(addpayment);
        addpayment.setVisible(false);
        addpayment.setVisible(true);
    }                                           

private void update_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_paymentActionPerformed
// TODO add your handling code here:
        updatepayment=new updatePayment();
        getContentPane().removeAll();
        add(updatepayment);
        updatepayment.setVisible(false);
        updatepayment.setVisible(true);
    }//GEN-LAST:event_add_paymentActionPerformed

private void delete_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_paymentActionPerformed
// TODO add your handling code here:
        deletepayment=new deletePayment();
        getContentPane().removeAll();
        add(deletepayment);
        deletepayment.setVisible(false);
        deletepayment.setVisible(true);
    }//GEN-LAST:event_delete_paymentActionPerformed

    private void add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_customerActionPerformed
// TODO add your handling code here:
        add_cust=new addCustomer();
        getContentPane().removeAll();
        add(add_cust);
        add_cust.setVisible(false);
        add_cust.setVisible(true);
    }

//GEN-LAST:event_add_customerActionPerformed
 private void update_customerActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
    
         updatecust=new updateCustomers();
        getContentPane().removeAll();
        add(updatecust);
      updatecust.setVisible(false);
     updatecust.setVisible(true);
    }                                            
                                            
 private void delete_customerActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
    
         deletecustomer=new deleteCustomer();
        getContentPane().removeAll();
        add(deletecustomer);
deletecustomer.setVisible(false);
deletecustomer.setVisible(true);
    }                                            


    private void view_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_paymentActionPerformed
// TODO add your handling code here:
        payment_view=new viewPayment();
        getContentPane().removeAll();
        add(payment_view);
        payment_view.setVisible(false);
        payment_view.setVisible(true);
        
    }//GEN-LAST:event_view_paymentActionPerformed

private void update_orderActionPerformed(java.awt.event.ActionEvent evt) {                                              // TODO add your handling code here:
         updateorder=new updateOrder();
        getContentPane().removeAll();
        add(updateorder);
       updateorder.setVisible(false);
       updateorder.setVisible(true);
    }                    
 
private void delete_orderActionPerformed(java.awt.event.ActionEvent evt) {                                              // TODO add your handling code here:
         deleteorder=new deleteOrder();
        getContentPane().removeAll();
        add(deleteorder);
       deleteorder.setVisible(false);
       deleteorder.setVisible(true);
    }      
  
 private void full_table_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_table_productActionPerformed
// TODO add your handling code here:
        product_view=new Product();
        getContentPane().removeAll();
        add(product_view);
        product_view.setVisible(false);
        product_view.setVisible(true);
        
        
    }//GEN-LAST:event_full_table_productActionPerformed

       private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void view_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_productActionPerformed
// TODO add your handling code here:
        product_view=new Product();
        getContentPane().removeAll();
        add(product_view);
        product_view.setVisible(false);
        product_view.setVisible(true);
        
        
    }//GEN-LAST:event_view_productActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void order_detail_by_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_detail_by_idActionPerformed
// TODO add your handling code here:
        idorder=new IDOrderDetail();
        getContentPane().removeAll();
        add(idorder);
        idorder.setSize(500,500);
        idorder.setVisible(false);
        idorder.setVisible(true);
    }//GEN-LAST:event_order_detail_by_idActionPerformed

    private void full_table_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_table_orderActionPerformed
// TODO add your handling code here:
        view_all_orders=new viewAllOrders();
        getContentPane().removeAll();
        add(view_all_orders);
        view_all_orders.setVisible(false);
        view_all_orders.setVisible(true);
    }//GEN-LAST:event_full_table_orderActionPerformed

    private void last_ten_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_ten_ordersActionPerformed
// TODO add your handling code here:
         view_few_orders=new viewFewOrders();
        getContentPane().removeAll();
        add(view_few_orders);
        view_few_orders.setVisible(false);
        view_few_orders.setVisible(true);
       
    }//GEN-LAST:event_last_ten_ordersActionPerformed

    private void last_ten_rawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_ten_rawActionPerformed
// TODO add your handling code here:
        rawfew=new RawFew();
        getContentPane().removeAll();
        add(rawfew);
        rawfew.setVisible(false);
        rawfew.setVisible(true);
        
    }//GEN-LAST:event_last_ten_rawActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_paymentActionPerformed

    private void full_order_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_order_detailActionPerformed
// TODO add your handling code here:
        view_full_order_detail=new viewOrderDetail();
        getContentPane().removeAll();
        add(view_full_order_detail);
        view_full_order_detail.setVisible(false);
        view_full_order_detail.setVisible(true);
        
    }//GEN-LAST:event_full_order_detailActionPerformed

    private void view_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_ordersActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_view_ordersActionPerformed

    private void last_ten_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_ten_productActionPerformed
// TODO add your handling code here:
        productfew=new ProductFew();
        getContentPane().removeAll();
        add(productfew);
        productfew.setVisible(false);
        productfew.setVisible(true);
        
    }//GEN-LAST:event_last_ten_productActionPerformed

    private void full_table_rawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_table_rawActionPerformed
// TODO add your handling code here:
        raw=new Raw();
        getContentPane().removeAll();
        add(raw);
        raw.setVisible(false);
        raw.setVisible(true);
    }//GEN-LAST:event_full_table_rawActionPerformed

    private void customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_customersActionPerformed

    private void view_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_customersActionPerformed
// TODO add your handling code here:
viewcustomer=new viewCustomers();
        getContentPane().removeAll();
        add(viewcustomer);
        viewcustomer.setVisible(false);
        viewcustomer.setVisible(true);


    }//GEN-LAST:event_view_customersActionPerformed
    
private void view_product_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_product_stockActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_view_product_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marketingHome().setVisible(true);

            }
        });
    }
   

   private javax.swing.JMenuItem add_customer;
    private javax.swing.JMenuItem add_order;
    private javax.swing.JMenuItem add_payment;
    private javax.swing.JMenu customers;
    private javax.swing.JMenuItem delete_customer;
 private javax.swing.JMenuItem delete_payment;
    private javax.swing.JMenuItem delete_order;
    private javax.swing.JMenuItem full_order_detail;
    private javax.swing.JMenuItem full_table_order;
   private javax.swing.JMenuItem full_table_product;
    private javax.swing.JMenuItem full_table_raw;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem last_ten_orders;
    private javax.swing.JMenuItem last_ten_product;
    private javax.swing.JMenuItem last_ten_raw;
    private javax.swing.JMenuItem order_detail_by_id;
    private javax.swing.JMenu orders;
    private javax.swing.JMenu payment;
    private javax.swing.JMenu product;
    private javax.swing.JMenu stock;
    private javax.swing.JMenuItem update_customer;
    private javax.swing.JMenuItem update_order;
    private javax.swing.JMenuItem update_payment;
    private javax.swing.JMenuItem view_customers;
    private javax.swing.JMenu view_order;
    private javax.swing.JMenu view_order_detail;
    private javax.swing.JMenu view_orders;
    private javax.swing.JMenuItem view_payment;
    private javax.swing.JMenuItem view_product;
    private javax.swing.JMenu view_product_stock;
    private javax.swing.JMenu view_raw_stack;
    // End of variables declaration                   
    
}
