import java.awt.Color;
import javax.swing.*;


/**
 *
 * @author  rishabh
 */
public class menu1 extends javax.swing.JFrame {
    JButton jb=new JButton("click");
    /** Creates new form menu */
    public menu1() {
      UIManager.put( "Menu.selectionBackground" , Color.green );
       UIManager.put( "MenuItem.selectionBackground" , Color.green );
  setExtendedState(this.MAXIMIZED_BOTH);
  //JPanel jpanel=new JPanel();
  //add(mainPanel);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        edit = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
     

        jMenu1.setText("file");
        jMenu2.setText("Menu");
        jMenuItem1.setText("Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem1);

        jMenu1.add(jMenu2);

        jMenu3.setText("Menu");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        edit.setText("edit");
        jMenuBar1.add(edit);

        jMenu5.setText("home");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);


        pack();
    }// </editor-fold>                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
        remove(mainPanel);
       // JButton jb=new JButton("click");
        //mainPanel.add(jb);
        //mainPanel.setVisible(false);
	//mainPanel.setVisible(true);
     //remove(mainPanel);
        //mainPanel.add(new panel1());
       add(new panel1());
       //mainPanel.removeAll();
       //mainPanel.setVisible(false);
       
        
    }                                          
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
               
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JMenu edit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration                   
    
}

 

